language: python
python:
    - '2.7'

script:
    - sed -e "s/__VERSION__/${TRAVIS_TAG}/" -i setup.py

deploy:
    provider: pypi
    distributions: sdist
    skip_cleanup: true
    on:
        tags: true
        branch: master
    user:
        secure: "swxlRMw6sPZfWmZ1pOLGie+/aMg2t5OxVvS46VU7R5yNVLrWo4voc89axs4LFhChuLllKcO68M9AENzGaOi81P1UbyIaxHOn5BK8gWXjrfZPUUlW2BxtCKCKUCbRDmjbrOlY6+a0QaZYCV77281lzedqy786vMavvqm+Mgb98pfwl5omOMieXNL0byOkyfR7y+l+gknk3ELLYfnBeJqFmVmyQCQHRuLxWKjpcQt83jAUz36HZazQH73W8YKfAwcCBN3EChSy/W/4Jb+Hy7mwpvaxk4CYrb8f6/76S3hq6SCJeu1M3tStEfHwfU24ORxKQRoFHSpyX8KIy2vjuVn7Klg/vaQGnroNULh1U7J6b+OQ6wmjJntc9fJSBhySHEGP6M5+Ej3W1BaZ2d6Zl54N9SiMKppZAh/tBjNeVDw5w0kmYmxHjWHra7e2xStrzpvlfT/PmX+SZPOdebQteyZR4WpiSROc3kr0itIoOK/utaeeFHenLEQJ+YQEPbVH1FrwwtIotRkqhm2XxjxMmi+i+/VsOtfGXjwZCToi3aq2L02gCnVZFjI0xWeRLqvq/XfGK+6bSy7gLjYu4w/aqI5rq1cfgP+zdxxadYQhD6uvp/Wepnz+klg5PS25QUZRqWZdMa/DAWzoZxdBKjjwwoQeBb7T61CEgKEeSc8m/dcNRyc="
    password:
        secure: "uWzPAhQ4UqUc2m5b8+hNu6OHNv5onZXA4gsynpsMceG5logJxKHERQmOgLbYkXPQ0MuzIRRr9HkbI6X6pQISaXZFAI5nU43bBd9VduB0qUqchmCOSigPSTBQ+GFBzDpYGwbt2PFZgKNYr6hhQ8DIahtBZ3n/ujkgDY19LPNQj2FIscfN7uQNLhzCUB1xOyy6vIYrcZqpOGmwGgqn4DY694rJjnUlKB6mHxuOR5ZYYHsVkQKHO8T0NlcEMbRJZtrjcxGfkLVsmHzFRoZfBhHQJp4YI07n+xcok4hxz00wvwIZNJlRimsISK+4nVopjbn3xGTHDIBeA8namipReFcbBEJR3Z8B97dIptYjBhknl53eynZUcyjuddId27EGHTStALWNJT1VX75yapmKMDwHh3YlkybocLhAk1zbaMbDgtnjxt9Bg75zY4ZNOjQXWHGhl9a+5u4W+CJbV45SfaAml/8RJ06EXNqNUk/nFvVW7VOjP7yEH4DrarvRY+1m701hlMeUXgHwvEuvUD3ZVlwaRH/2Aj4PiCwFXSZgXDCFOFz9I06iQHvUYDjxFHbarjM2xvOhgcVos5yD27VwTBcoSG2qooZqhK1eAnOozr3OIihryvhUuXotIcmhcusB47Agw0MAyH7/rFSSgijeBHbdBJR6C1DFwyvLfYVVr5eVXWs="
