language: python
python:
    - '2.7'

script:
    - sed -e "s/__VERSION__/${TRAVIS_TAG}/" -i setup.py

deploy:
    provider: pypi
    distributions: sdist
    skip_cleanup: true
    on:
        tags: true
        branch: master
    user: cseelye
    password:
        secure: "uWzPAhQ4UqUc2m5b8+hNu6OHNv5onZXA4gsynpsMceG5logJxKHERQmOgLbYkXPQ0MuzIRRr9HkbI6X6pQISaXZFAI5nU43bBd9VduB0qUqchmCOSigPSTBQ+GFBzDpYGwbt2PFZgKNYr6hhQ8DIahtBZ3n/ujkgDY19LPNQj2FIscfN7uQNLhzCUB1xOyy6vIYrcZqpOGmwGgqn4DY694rJjnUlKB6mHxuOR5ZYYHsVkQKHO8T0NlcEMbRJZtrjcxGfkLVsmHzFRoZfBhHQJp4YI07n+xcok4hxz00wvwIZNJlRimsISK+4nVopjbn3xGTHDIBeA8namipReFcbBEJR3Z8B97dIptYjBhknl53eynZUcyjuddId27EGHTStALWNJT1VX75yapmKMDwHh3YlkybocLhAk1zbaMbDgtnjxt9Bg75zY4ZNOjQXWHGhl9a+5u4W+CJbV45SfaAml/8RJ06EXNqNUk/nFvVW7VOjP7yEH4DrarvRY+1m701hlMeUXgHwvEuvUD3ZVlwaRH/2Aj4PiCwFXSZgXDCFOFz9I06iQHvUYDjxFHbarjM2xvOhgcVos5yD27VwTBcoSG2qooZqhK1eAnOozr3OIihryvhUuXotIcmhcusB47Agw0MAyH7/rFSSgijeBHbdBJR6C1DFwyvLfYVVr5eVXWs="
