language: python
python:
    - '2.7'
env:
    global:
        - secure: "i/cMwXU3vT420mxGeFW/1jGbssDPpRdZ/WKIX49bGx9lbvnr78Vs9lLp8H7pBOYuiFSDSEbKORzOpIgju+hfwruF112X8j3yEicjOo3QqOCSLyYUVfK1gsysD4UigLVxPbZrPjnDPBxeE7aowKcq8j8G+g6H/NdJgvaBqN/STHpngjLBVI0Qk+TVoz9hE1x8tZ8eNcXkFw6zFje8A/0CQ4bARUaR2tG5hwBapvFxoHSVKCgSbQR1NnY8WgouNV9nlfGWqtKjs5E6lYgHw2bncYHYoT4K4Zkn4atmOBgue6wbAOKiatKuXbiPgQcxv2dQ4zNBfuPInCdJUJhkDIz0snDdsnlB3yQimOTr5GQvT5wm5bUbcQ2merptteHs+3OdzB4NTum++4GR8LMK/vwiPUZ/0oleKuoJvejfZcdj+/AuU8oQcqu2kjP4R0MpaByvqgPGHPTM3cMpAKOW9zerIoW8qb1of/3qic7yct8t3UWvYszfVCBoeRB60VzobfYeStZUJsYhLB2fr90JB5x0cNYDbJo0MAgNAhgx68lTWeEUhJOSCnPp0RL/G7e9KPIbNORZth3JE3kU9dvUi2UcptzCwiQOrjomL/X5SJ2/DMK0rHZyBpf6iST1/XtSEaaha5ejyVKyN/FJcz6hTpQx0qCH6Sn/sUw7n2hwLcFEsqY="
        - secure: "mobBCfKsH9rVYOsIqdg+ydjgBEK15wLxkLEbQ7Evds87gf2e4xYmFAq/SeVuxrZjwQyWGJOigSC+SmVYvic1jYKrdo9S3y1FkjkEaLjmkYNxg64/PZJnjSEzcp1Ha29VzKMjzaumoG9H3V9smIwxdPbrR4mihzFd2W9syY9jEW0othjHoLAJ0SyWsh3HtloHq750rhe8QEufpOLWhOt5og21UQW66Aeh/apQKgkdDxC1UF9MyOt9Gj56ykaTYT0HOXmOynUvz72HUBpsAUkADQ+433+E4WOQ9lkAQU/1k2vdfIaW2avs1es9loi+AqjZNoH8NRd06GPZA4BNQhDxuCvTvpEaxpr4gdOx3oMSxbx6agB31tPjA/MkU3fHWK6AdF/NMGIOtItT3NNBJkhCU5BfXjcwYwdKSYEGcHfwWp8n+CwN5DxRW+7bTBrztEeIlLOpg2+XlXY3+OO220FfsBzOVwksdcE15raR67Ks1inYqIFR6RUJJIuGTPby1iAJ8fm9WxfYroJUsYi8v5RqFCFgLr+pmHWR0vXLMj0E8pCLPW1XNBhC0vIEbwVkwG7ciPHpYI7gNDlVtSNN9fJTBrk6JKqzI3Z90uhLuTh73lMDlN+cwdW7ExcqRaD5KP2TmgY8NQAkYrQGGi7CC9J3dOsZ1zn3E0cqGGi4XIlYfPk="

script:
    - sed -e "s/__VERSION__/${TRAVIS_TAG}/" -i setup.py
deploy:
    provider: pypi
    distributions: sdist
    skip_cleanup: true
    on:
        tags: true
        branch: master
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
