language: python
python:
- '2.7'
script:
- sed -e "s/__VERSION__/${TRAVIS_TAG}/" -i setup.py
deploy:
  provider: pypi
  distributions: sdist
  skip_cleanup: true
  on:
    tags: true
    branch: master
  user: cseelye
  password:
    secure: lbsPHLV/+DGTZd0bKWvsr+6W7RzLBmKux7xSY05AWRWUzbmb+C7otY3NNgxw1pOzyvGyxGeC0iHUyo1i7T/YMIiDLZYIM8j33UWcNtq3yfZdwVGndCVuwzry3dWNbOP1Ft5bTLP95aOEEshJJy+B++gYrShSITbsXh077uXLI+U5xWY3jknPwpnM000nKbtpGj3Syk8qLvr982qUUr5VAyqocY9WNVoSP4LAyNpsAJBp4A/IkBY3rWfjH4Df+JE10lqO44XLoef64/wwwpgHb4v/J4USDG7n1lR7jA6J3YGLEN+OO6RlmaW0F+/2SC/zuP6H+Sb7gmjXW1sih9XqK8BL9AzGuNRPzimzqwPA2W9l7k1O7sY7KZsn72XED3Im6uFb3YhVqsrzVqYVjmw/7PTOXwklq8pLDDa3vXw45xtIwYKvpLjM4IlgodYum0H3SpMAbM92II3TjRB/G/TYfUV8iahLGV6HFHobEYXcV9+H7qLByvbeC7UWI4Wekjj5wXlZeue2JFX38oSwxkL0gX/1ehdU3IMYz4AYDNHjMMVbHDJmc0eBJpVQjb3FYg80jQ/BUJ8cl05FIYs3mLjhQJ3BmTpfnN+QahwzG2ajdgSnk+RqowYTgOle4/COXSfq90VeEU1/DdosJ6bTEea3CdiZV8GR+1CUX12eUMHdwNo=
