language: python
python:
- '2.7'
script:
- sed -e "s/__VERSION__/${TRAVIS_TAG}/" -i setup.py
deploy:
  provider: pypi
  distributions: sdist
  skip_cleanup: true
  on:
    tags: true
    branch: master
  user: cseelye
  password:
    secure: mWaz67HJ0ttqMTldakFCnuhZGkQvTjIVgsUg8RvaFRzkxBmEUfwNB6L4b/ZO8+abpqsZuiJyexU851SHj4/NMIweEP50fYjmE/2FBFx5XBGKBu+9+l3HBMhh+5ipen5yAsal9AsL91/jr2zThbSI+JL1A+yFvPdeQJeu5elTkYVs/+9SUo/O7Z0S1uNCg2irnXwhxi2x7V7+EporFSPQ9XeZglinl8B9My9ios+xL/jPGuGNLnYpU5/DvNCRbFnrnVlWo3nN4Vpp2/s3DH4qkgAlL+P1ANm23vYPOm41/Pihnj8ZQQyDThmULLtQBUBTaBZrD61AqmNPQRYUpaOh2qQLERAgXBV65ctTwRLbCbYQ8Wz4w0YmOP2dxn65GvHusl983mnexqGBRbNK639Qsi8DhkTzUenYvrH6apydZM8CRnUqygbU1rn6cMpJDntJhRufAbzZXeBB1umjSvy4NE84asLoMtFMbsXyLT3si3if0cvWyEXbknBiqjpEhYPnLUUgwwN/yFf4RNexhQ00uWFzEfmjeDZH+DT1FtMXoUoFAzKqa1WbNe3Qqr/Dce3GVyd4Nb3E3EcJiv+xERoriFLsSAhdPJN+iixmam2BHoR9Cc9Ukpw/gKa3EAxrlit/PIaHyUsCvOUIBDBA0d5pSH24Nyz5c7fSNHB3ik+kHGw=
