language: python
python:
- '2.7'
script:
- sed -e "s/__VERSION__/${TRAVIS_TAG}/" -i setup.py
deploy:
  provider: pypi
  distributions: sdist
  skip_cleanup: true
  on:
    tags: true
    branch: master
  user: cseelye
  password: idyBd5yB5S5BwWTt
