language: python
python:
- '2.7'
script:
- sed -e "s/__VERSION__/${TRAVIS_TAG}/" -i setup.py
deploy:
  provider: pypi
  distributions: sdist
  skip_cleanup: true
  on:
    tags: true
    branch: master
  user: cseelye
  password:
    secure: ob2RwLuyKhbcnevz33vHNxqc9MLI0/bY67MYV9Q2KAnyoYpeoG/7Pce7XBmZvoQxP8sFe5GJYyWAlN9wXzF0lg9mR4XxhfRiiEBRedJYCkKl8hq3OstEuxmJzP+oTXVC167/PK2PWo81sfqsG1kI5f1aROF60fA96Z9aorXucOHkokivp4Nqa3jVVbT3Ao+eBDd8RmYs4SKZuhoqSaDdlRLg5ZJU/sWerkhG/U61CgdwQcLGY+cwHkbhyomU0ngpG5mBH2+cx+syovd1LNzKebkfG9UWwndL7ItlY+sFYrYW97d/TnSxeR4/DtlEHlIYQ7dMyMo96rqHojmG4cdZiJpFs9g4hkdHAstKxtrXYvZ66BAXXWeIqgAG9MCN/xNioD57Y86S5t7AjPeh8HkrWlJqbGqWn2s1aIBbaYESNVJgGg/rLees2rOhj64sfite7F5NGIFrIbG+j4U/L5vLYabLLr9ZZNqQ0EqynYMS69+nu6Cbf4E6MtUI1uoj+YfTPfI2aZpQ23B/sWElD+tQcN4rFcDcVM+thGcZWsiOGbrC+LzVwbMWb7Q7EegfUKhtj1GlLFXWnkNMgfBxeKnCHP7SharOe5zDGU5WxPM1ngoHApXW0+GXKdCjXPjCHQl3M6A55OLuGWp+TtMO1mkn43GfML+YmTLA2tJZIzPkr0M=
